#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process
# Requirement: You cannot use kill or killall

pkill -f 4-to_infinity_and_beyond
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing

