#!/usr/bin/env bash
# Script to change nginx privileges

sudo service nginx stop
sed -i "s/#user.+\;/user nginx;/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod +rw /etc/nginx/nginx.conf
for pid in $(pidof apache2); do
    kill "$pid"
done 
su -c 'service nginx start' nginx
