#!/usr/bin/env bash
# A script that creates an RSA key pair.
# Requirements:
# Name of the created private key must be 'schoo'l
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase 'betty'

ssh-keygen -b 4096 -f school -N betty
